services:
  postgres:
    image: postgres:15
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "${POSTGRES_PORT}:5432"

  loader:
    build:
      context: ./python-loader
      dockerfile: Dockerfile
    image: dbt-elt-retail-loader:latest
    depends_on:
      - postgres
    environment:
      DB_HOST: ${DB_HOST}
      DB_PORT: '${DB_PORT}'
      DB_NAME: ${DB_NAME}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
    volumes:
      - data:/data
      - ./python-loader:/app
    command: ["bash"]

  metabase:
    image: metabase/metabase:latest
    restart: unless-stopped
    ports:
      - "${METABASE_PORT}:3000"
    environment:
      MB_DB_FILE: ${MB_DB_FILE}
    volumes:
      - metabase-data:/metabase-data

volumes:
  pgdata:
  metabase-data:
  data:
